services:
  db:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_storage:/var/lib/mysql
    networks:
      - main_shared_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mysql_ui
    restart: always
    environment:
      PMA_HOST: db
      # ตัวแปรสำคัญเพื่อให้เข้าผ่าน /pma ได้ถูกต้อง
      PMA_ABSOLUTE_URI: http://localhost/pma/
    networks:
      - main_shared_network
    # ไม่ต้องเปิด ports ออกข้างนอก เพราะจะให้ Nginx ในโปรเจกต์เว็บเป็นคนเรียก

networks:
  main_shared_network:
    external: true

volumes:
  db_storage: