version: '3.8'

services:
  db:
    image: park104/database_server_docker:mysql
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}  # เปลี่ยนเป็นรหัสที่คุณต้องการ
      MYSQL_DATABASE: teamder_db
    volumes:
      - db_storage:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - main_shared_network

  phpmyadmin:
    image: park104/database_server_docker:pma
    container_name: mysql_ui
    restart: always
    environment:
      PMA_HOST: db
      PMA_ABSOLUTE_URI: https://dev.teamder.online/pma/
      TRUSTED_PROXIES: 0.0.0.0/0
    networks:
      - main_shared_network

networks:
  main_shared_network:
    external: true

volumes:
  db_storage: